version: '3.2'

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: .
      dockerfile: Dockerfile.dev
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
    depends_on:
      - db
    env_file:
      - .env
    # Comment out these volumes in production
    environment:
        XDEBUG_CONFIG: remote_host=192.168.0.192
    volumes:
      - .:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./var:/srv/api/var:rw

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - "8080:80"

  db:
    # In production, you may want to use a managed database service
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data: {}
